tnved/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tnvedcode.urls')),



]

tnvedcode/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('search/<str:code>/', views.PermissionSearchView.as_view(), name='permission-search'),
    path('create_tnved_code/', views.create_tnved_code, name='create_tnved_code'),
    path('create_organization/', views.create_organization, name='create_organization'),
    path('create_permission/', views.create_permission, name='create_permission'),
    path('delete_code/<int:code>/', views.delete_tnved_code, name='delete_code'),
    path('delete_organization/<str:name>/', views.delete_organization, name='delete_organization'),
    path('delete_permission/<int:code>/<str:organization_name>/', views.delete_permission, name='delete_permission'),
    path('success/', views.success_view, name='success'),
    path('notsuccess/', views.notsuccess_view, name='notsuccess'),
    path('code/<int:code>/update/', views.update_code, name='update_code'),
    path('organization/<str:name>/update/', views.update_organization, name='update_organization'),
    path('update_permission/<int:code>/<str:organization_name>/', views.update_permission, name='update_permission'),
    path('codes/', views.all_codes, name='all_codes'),
    path('organizations/', views.all_оrganizations, name='all_оrganizations'),
    path('permissions/', views.all_permissions, name='all_permissions'),


]

tnvedcode/models.py
from django.db import models
IMPORT_STATUS_CHOICES = [
        ('+', '+'),
        ('-', '-'),
        ('x', 'x'),
    ]


class TnvedCode(models.Model):
    IMPORT_STATUS_CHOICES = [
        ('+', '+'),
        ('-', '-'),
        ('x', 'x'),
    ]

    code = models.IntegerField(unique=True, verbose_name='Код товара')
    name = models.CharField(max_length=255, verbose_name='Наименование группы товара')
    import_status_legal_private = models.CharField(max_length=1, choices=IMPORT_STATUS_CHOICES, default='-',
                                                   verbose_name='Статус ввоза для юридических лиц частных компаний')

    import_status_individual_private = models.CharField(max_length=1, choices=IMPORT_STATUS_CHOICES, default='-',
                                                        verbose_name='Статус ввоза для физических лиц частных компаний')

    def __str__(self):
        return f'{self.code}'


class Organization(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Название организации')

    def __str__(self):
        return self.name


class Permission(models.Model):



    code = models.ForeignKey(TnvedCode, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    import_status_legal = models.CharField(max_length=1, choices=IMPORT_STATUS_CHOICES, default='-', verbose_name='Статус ввоза для юридических лиц')
    import_status_individual = models.CharField(max_length=1, choices=IMPORT_STATUS_CHOICES, default='-', verbose_name='Статус ввоза для физических лиц')


    class Meta:

        unique_together = ['code', 'organization']

tnvedcode/forms.py
from django import forms
from .models import TnvedCode, Organization, Permission

class TnvedCodeForm(forms.ModelForm):
    class Meta:
        model = TnvedCode
        fields = '__all__'

class OrganizationsForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = '__all__'



class PermissionForm(forms.ModelForm):
    class Meta:
        model = Permission
        fields = '__all__'

tnvedcode/views.py
from rest_framework import generics
from django.shortcuts import render, redirect
from .forms import TnvedCodeForm, OrganizationsForm, PermissionForm
from .models import Permission,TnvedCode, Organization

from .serializers import PermissionSerializer
from django.shortcuts import get_object_or_404
from django.http import HttpResponse


class PermissionSearchView(generics.ListAPIView):
    serializer_class = PermissionSerializer

    def get_queryset(self):
        code = self.kwargs.get('code', None)
        if code is not None:
            try:
                tnved_code = TnvedCode.objects.get(code=code)
                permissions = Permission.objects.filter(code=tnved_code)
                return permissions
            except TnvedCode.DoesNotExist:
                return Permission.objects.none()
        else:
            return Permission.objects.none()

    def list(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        context = {'permissions': queryset}
        return render(request, 'tnvedcode/permission_search.html', context)




def create_tnved_code(request):
    if request.method == 'POST':
        form = TnvedCodeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success')
    else:
        form = TnvedCodeForm()
    return render(request, 'tnvedcode/create_code.html', {'form': form})


def create_organization(request):
    if request.method == 'POST':
        form = OrganizationsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success')
    else:
        form = OrganizationsForm()
    return render(request, 'tnvedcode/create_organization.html', {'form': form})

def create_permission(request):
    if request.method == 'POST':
        form = PermissionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success')
    else:
        form = PermissionForm()
    return render(request, 'tnvedcode/create_permission.html', {'form': form})


def delete_tnved_code(request, code):
    try:
        tnved_code = TnvedCode.objects.get(code=code)
    except TnvedCode.DoesNotExist:
        return redirect('notsuccess')

    if request.method == 'POST':

        tnved_code.delete()
        return redirect('success')

    return render(request, 'tnvedcode/delete_code.html', {'tnved_code': tnved_code})


def delete_organization(request, name):
    try:
        organization = Organization.objects.get(name=name)
    except Organization.DoesNotExist:
        return redirect('notsuccess')

    if request.method == 'POST':
        organization.delete()
        return redirect('success')

    return render(request, 'tnvedcode/delete_organization.html', {'organization': organization})


def delete_permission(request, code, organization_name):
    try:
        permission = Permission.objects.get(code__code=code, organization__name=organization_name)
    except Permission.DoesNotExist:
        return redirect('notsuccess')

    if request.method == 'POST':
        permission.delete()
        return redirect('success')

    return render(request, 'tnvedcode/delete_permission.html', {'permission': permission})



def update_code(request, code):
    try:
        tnved_code = TnvedCode.objects.get(code=code)
    except TnvedCode.DoesNotExist:
        return redirect('notsuccess')

    if request.method == 'POST':
        form = TnvedCodeForm(request.POST, instance=tnved_code)
        if form.is_valid():
            form.save()
            return redirect('success')
    else:
        form = TnvedCodeForm(instance=tnved_code)

    return render(request, 'tnvedcode/update_code.html', {'form': form, 'code': code})


def update_organization(request, name):
    try:
        organization = Organization.objects.get(name=name)
    except Organization.DoesNotExist:
        return redirect('notsuccess')

    if request.method == 'POST':
        form = OrganizationsForm(request.POST, instance=organization)
        if form.is_valid():
            form.save()
            return redirect('success')
    else:
        form = OrganizationsForm(instance=organization)

    return render(request, 'tnvedcode/update_organizations.html', {'form': form})

def update_permission(request, code, organization_name):
    try:
        permission = Permission.objects.get(code__code=code, organization__name=organization_name)
    except Permission.DoesNotExist:
        return redirect('notfound')

    if request.method == 'POST':
        form = PermissionForm(request.POST, instance=permission)
        if form.is_valid():
            form.save()
            return redirect('success')
    else:
        form = PermissionForm(instance=permission)

    return render(request, 'tnvedcode/update_permission.html', {'form': form, 'permission': permission})

def all_codes(request):
    tnved_codes = TnvedCode.objects.all()
    return render(request, 'tnvedcode/all_codes.html', {'tnved_codes': tnved_codes})

def all_оrganizations(request):
    organizations = Organization.objects.all()
    return render(request, 'tnvedcode/all_organizations.html', {'organizations': organizations})

def all_permissions(request):
    permissions = Permission.objects.all()
    return render(request, 'tnvedcode/all_permissions.html', {'permissions': permissions})







def success_view(request):
    return render(request, 'tnvedcode/success.html')

def notsuccess_view(request):
    return render(request, 'tnvedcode/notsuccess.html')

templates/tnvedcode/all_codes.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="mb-3">
            <input type="text" id="searchInput" class="form-control" placeholder="Введите код для поиска">
        </div>

        <ul class="list-group" id="tnvedList">
            {% for code in tnved_codes %}

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ code.code }}</h5>
                        <p class="card-text">{{ code.name }}</p>
                    </div>
                    <div class="card-footer d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <form method="post" action="{% url 'delete_code' code=code.code %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger me-2">Удалить</button>
                            </form>
                            <form method="post" action="{% url 'update_code' code=code.code %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-warning">Изменить</button>
                            </form>
                        </div>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
    const searchInput = document.getElementById('searchInput');
    const tnvedList = document.getElementById('tnvedList');

    searchInput.addEventListener('input', function() {
        const searchQuery = searchInput.value.toLowerCase();

        Array.from(tnvedList.children).forEach(function(card) {
            const codeText = card.querySelector('.card-title').innerText.toLowerCase();
            const nameText = card.querySelector('.card-text').innerText.toLowerCase();

            // Проверяем совпадение по коду или названию
            if (codeText.includes(searchQuery) || nameText.includes(searchQuery)) {
                card.style.display = 'block';
            } else {
                card.style.display = 'none';
            }
        });
    });
});

    </script>
{% endblock %}

templates/tnvedcode/all_organizations.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="mb-3">
            <input type="text" id="searchInput" class="form-control" placeholder="Введите имя организации для поиска">
        </div>

     <ul class="list-group" id="organizationList">
            {% for organization in organizations %}
                <li class="list-group-item">
                    <div class="card">
                        <div class="card-body d-flex justify-content-between align-items-center">
                            <h5 class="card-title">{{ organization.name }}</h5>
                            <div class="d-flex">
                                <i class="bi bi-trash me-2" data-organization-id="{{ organization.id }}" onclick="deleteOrganization(this)"></i>
                                <i class="bi bi-pencil me-2" data-organization-id="{{ organization.id }}" onclick="editOrganization(this)"></i>
                                <div class="btn-group" role="group">
                                    <form method="post" action="{% url 'delete_organization' name=organization.name %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">Удалить</button>
                                    </form>
                                    <form method="post" action="{% url 'update_organization' name=organization.name %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-warning">Изменить</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const searchInput = document.getElementById('searchInput');
            const organizationList = document.getElementById('organizationList');

            searchInput.addEventListener('input', function() {
                const searchQuery = searchInput.value.toLowerCase();

                Array.from(organizationList.children).forEach(function(card) {
                    const nameText = card.querySelector('.card-title').innerText.toLowerCase();

                    if (nameText.includes(searchQuery)) {
                        card.style.display = 'block';
                    } else {
                        card.style.display = 'none';
                    }
                });
            });

            function deleteOrganization(icon) {
                const organizationId = icon.dataset.organizationId;
                console.log('Delete organization with ID:', organizationId);
            }

            function editOrganization(icon) {
                const organizationId = icon.dataset.organizationId;

                console.log('Edit organization with ID:', organizationId);
            }
        });
    </script>
{% endblock %}

templates/tnvedcode/all_permissions.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="mb-3">
            <input type="text" id="searchInput" class="form-control" placeholder="Введите код или название организации для поиска">
        </div>

        <ul class="list-group" id="permissionList">
            {% for permission in permissions %}
                <li class="list-group-item">
                    <div class="card">
                        <div class="card-body d-flex justify-content-between align-items-center">
                            <h5 class="card-title">{{ permission.code.code }} - {{ permission.organization.name }}</h5>

                            <div class="d-flex">
                                <div class="btn-group" role="group">
                                    <form method="post" action="{% url 'delete_permission' code=permission.code.code organization_name=permission.organization.name %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">Удалить</button>
                                    </form>

                                    <form method="post" action="{% url 'update_permission' code=permission.code.code organization_name=permission.organization.name %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-warning">Изменить</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const searchInput = document.getElementById('searchInput');
            const permissionList = document.getElementById('permissionList');

            searchInput.addEventListener('input', function() {
                const searchQuery = searchInput.value.toLowerCase();

                Array.from(permissionList.children).forEach(function(li) {
                    const card = li.querySelector('.card');
                    const codeText = card.querySelector('.card-title').innerText.toLowerCase();
                    const organizationText = card.querySelector('.card-title').innerText.toLowerCase();

                    if (
                        codeText.includes(searchQuery) ||
                        organizationText.includes(searchQuery)
                    ) {
                        li.style.display = 'block';
                    } else {
                        li.style.display = 'none';
                    }
                });
            });
        });
    </script>
{% endblock %}

templates/tnvedcode/create_code.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.tabler.io/1.8.0/dist/css/tabler.min.css" rel="stylesheet">

    <!-- Дополнительные стили для карточки -->
    <style>
        body {
            background-color: #f5f6f8;
        }

        .card-container {
            max-width: 400px;
            margin: 50px auto;
        }

        .card {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }

        form {
            margin-top: 20px;
        }
    </style>
</head>
<body>

    <div class="page">
        <div class="content">
            <div class="container-xl">

                <div class="card-container">
                    <div class="card">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <script src="https://cdn.tabler.io/1.8.0/dist/js/tabler.min.js"></script>
</body>
</html>

templates/tnvedcode/create_organization.html
{% extends 'base.html' %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        .card {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            width: 400px;
            margin: 10px;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        label {
            margin-bottom: 8px;
            font-weight: bold;
        }

        input, select {
            padding: 8px;
            margin-bottom: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }

        a {
            color: #3498db;
            text-decoration: none;
            margin-top: 10px;
            display: inline-block;
        }

        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>

  <div class="page">
    <div class="content">
      <div class="container-xl">
        <div class="card-container">
          <div class="card">
            <form method="post">
              {% csrf_token %}


              <div class="mb-3">
                <label class="form-label" for="{{ form.name.id_for_label }}">Организация Лицензиар/Эксперт</label>
                {{ form.name }}
              </div>

              <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>
</html>
{% endblock %}

templates/tnvedcode/delete_code.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h2>Delete Confirmation</h2>
        <p>Are you sure you want to delete code {{ tnved_code.code }} - {{ tnved_code.name }}?</p>

        <form method="post" action="{% url 'delete_code' code=tnved_code.code %}">
            {% csrf_token %}
            <button type="submit" name="confirm_delete" class="btn btn-danger">Confirm Delete</button>
            <a href="{% url 'remaining_codes' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
{% endblock %}

templates/tnvedcode/delete_organization.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Organization</title>
</head>
<body>
    <h2>Delete Organization</h2>
    <p>Вы уверены, что хотите удалить организацию "{{ organization.name }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit">Удалить</button>
    </form>

    <a href="{% url 'success' %}">Отмена</a>  <!-- Замените 'your_redirect_view' на ваш URL для перенаправления -->
</body>
</html>

templates/tnvedcode/delete_permission.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Permission</title>
</head>
<body>
    <h2>Delete Permission</h2>
    <p>Вы уверены, что хотите удалить разрешение для кода товара {{ permission.code.code }} и организации "{{ permission.organization.name }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit">Удалить</button>
    </form>

    <a href="{% url 'success' %}">Отмена</a>
</body>
</html>

templates/tnvedcode/notsuccess.html
{% extends 'base.html' %}

{% block content %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success</title>
</head>
<body>
    <h2>Операция успешно выполнена</h2>
    <p>Ваш запрос был не был обработан.</p>
    <!-- Дополнительные сведения или ссылки, если необходимо -->
</body>

{% endblock %}

templates/tnvedcode/permission_search.html
{% extends 'base.html' %}

{% block content %}
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>

    <title>Permission Search</title>
    <style>
        body {
            font-family: 'Inter', sans-serif;
            background-color: #e6e7eb;
            color: #1e272e;
            margin: 0;
            padding: 0;
            height: 100vh;
            display: flex;
            flex-direction: column;
        font-family: 'Inter', sans-serif;
        }


        .container {

            margin: auto;
            max-width: 100%;
        }

        .search-container {
            display: flex;
            align-items: center;
            background-color: #f4f6f9;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 20px;

        }

        .search-input {
            border: none;
            outline: none;
            flex-grow: 1;
            padding: 8px;
            border-radius: 5px;
        }

        .search-button {
            background-color: #6c757d;
            color: #fff;
            border: none;
            border-radius: 5px;
            padding: 8px;
            cursor: pointer;
            margin-left: 10px;
        }

        .table-custom {
            width: 100%;
            background-color: #fff;
            border: 1px solid #d2dae2;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }

        .table-custom thead th {
            border-bottom: 2px solid #d2dae2;
            font-weight: 600;
            color: #5e6f7a;
            background-color: #f4f6f9;
        }

        .table-custom th, .table-custom td {
            padding: 1rem;
            vertical-align: top;
            border-top: 1px solid #d2dae2;
        }

        .table-custom tbody tr:hover {
            background-color: #ebf5fb;
        }

        .table-custom tbody td {
            position: relative;
        }

        .table-custom tbody td::before {
            content: "";
            display: block;
            position: absolute;
            top: 0;
            left: 0;
            height: 100%;
            width: 10px;
            background-color: #3498db;
            opacity: 0.8;
            z-index: -1;
        }



    </style>
</head>

<body>



<div class="container mt-10">
    <div class="search-container">
        <input type="text" class="form-control search-input" id="codeInput" placeholder="Введите код">

        <button class="btn search-button" onclick="searchPermissions()">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrow-right" width="24"
                height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path d="M5 12l14 0" />
                <path d="M13 18l6 -6" />
                <path d="M13 6l6 6" />
            </svg>
        </button>
    </div>


    <div class="container mt-10">

        <div class="row">
            <!-- First Table -->
            <div class="col-md-">
                <div class="table-responsive">
                   <table class="table-custom table table-hover" id="permissionsTable">
                <thead>
                    <tr>
                        <th rowspan="2">Наименование раздела</th>
                        <th colspan="{{ permissions.count }}">{{ permissions.0.code }}:{{ permissions.0.code.name }}</th>
                        <th colspan="{{ permissions.count }}">Сертификат соответствия/Декларация соответствияа</th>

                    </tr>
                </thead>

                    <tr>
                        <td class="last-column">Организация Лицензиар/Эксперт</td>
                        {% for permission in permissions %}
                            <th>{{ permission.organization.name }}</th>
                        {% endfor %}
                        <th class="last-column">Частные компании</th> <!-- Добавлена новая колонка -->
                    </tr>


                    <tr>
                        <td class="last-column">Документы для юр. лиц</td>
                        {% for permission in permissions %}
                            <td>{{ permission.get_import_status_legal_display }}</td>
                        {% endfor %}
                        <td>{{ permissions.0.code.import_status_legal_private }}</td> <!-- Добавлена новая ячейка -->
                    </tr>

                    <tr>
                        <td class="last-column">Документы для физ. лиц</td>
                        {% for permission in permissions %}
                            <td>{{ permission.get_import_status_individual_display }}</td>
                        {% endfor %}
                        <td class="last-column">{{ permissions.0.code.import_status_individual_private }}</td> <!-- Добавлена новая ячейка -->
                    </tr>

            </table>
                </div>
            </div>

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"></script>
            
    <script>
        function searchPermissions() {
            var codeInput = $('#codeInput');
            var scrollPosition = codeInput.scrollTop(); // Запоминаем положение скролла
            var code = codeInput.val();
            $.ajax({
                url: '/search/' + code + '/',
                method: 'GET',
                success: function(data) {
                    var tableHtml = $(data).find('#permissionsTable').html();
                    var secondTableHtml = $(data).find('#secondPermissionsTable').html();

                    if (tableHtml.trim() !== "") {
                        $('#permissionsTable').html(tableHtml);
                    } else {
                        $('#permissionsTable').remove();
                    }

                    if (secondTableHtml.trim() !== "") {
                        $('#secondPermissionsTable').html(secondTableHtml);
                    } else {
                        $('#secondPermissionsTable').remove();
                    }
                },
                error: function(error) {
                    console.error(error);
                }
            });
        }


    </script>
</body>
{% endblock %}

templates/tnvedcode/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success</title>
</head>
<body>
    <h2>Операция успешно выполнена</h2>
    <p>Ваш запрос был успешно обработан.</p>
    <!-- Дополнительные сведения или ссылки, если необходимо -->
</body>
</html>